"""Test that seed docs generated by init-vault-structure include mirror contracts and CLI location."""

from __future__ import annotations

from pathlib import Path

from chronicle_pipeline.cli import main


def test_seed_docs_contain_mirror_contracts_and_cli_paths(chronicle_dir: Path) -> None:
    code = main(["init-vault-structure", "--chronicle-dir", str(chronicle_dir), "--refresh-skills"])
    assert code == 0

    claude_md = (chronicle_dir / "CLAUDE.md").read_text(encoding="utf-8")
    conventions_md = (chronicle_dir / "_system/conventions.md").read_text(encoding="utf-8")
    retrieval_skill = (chronicle_dir / ".claude/skills/retrieval-format/SKILL.md").read_text(encoding="utf-8")
    maintenance_skill = (chronicle_dir / ".claude/skills/vault-maintenance/SKILL.md").read_text(encoding="utf-8")

    # CLAUDE.md must mention kb-sync / mirrors anti-fight rule and CLI path
    assert "kb-sync" in claude_md or "Mirrors" in claude_md
    assert "chronicle-pc/.venv/bin/chronicle" in claude_md or "CHRONICLE_BIN" in claude_md
    assert "source:" in claude_md

    # conventions.md must document the mirror frontmatter contract
    assert "source:" in conventions_md or "source" in conventions_md
    assert "ingest_tier" in conventions_md
    assert "source_rewrite" in conventions_md

    # SKILL_RETRIEVAL must check serve.json / PID liveness before preferring serve
    assert "serve.json" in retrieval_skill

    # SKILL_MAINTENANCE must mention kb-sync / kb-audit as mirror tools
    assert "kb-sync" in maintenance_skill
    assert "kb-audit" in maintenance_skill
