"""Regenerate root Upcoming.md from unchecked, dated tasks in knowledge notes.

Upcoming.md is derived/rebuildable (see CONTRACT.md write-ownership table):
the source-note checkbox is SoT, this file is a whole-file regen, and UI
edits to it are overwritten on next regenerate.
"""

from __future__ import annotations

import logging
import re
from calendar import month_name
from collections import defaultdict
from datetime import date
from pathlib import Path

from . import path_map
from .notes import write_if_changed

log = logging.getLogger("chronicle.upcoming")

UPCOMING_PATH = "Upcoming.md"

# "- [ ] description 📅 YYYY-MM-DD" per _system/conventions.md task format
_TASK_RE = re.compile(
    r"^[ \t]*-\s\[\s\]\s(?P<desc>.+?)\s*📅\s*(?P<date>\d{4}-\d{2}-\d{2})\s*$",
    re.MULTILINE,
)


def _title_for(rel: str) -> str:
    return Path(rel).stem.replace("-", " ").replace("_", " ")


def find_tasks(root: Path) -> list[dict]:
    """Scan all knowledge markdown for unchecked dated tasks."""
    tasks: list[dict] = []
    for rel, abs_path in path_map.iter_knowledge_md(root):
        try:
            text = abs_path.read_text(encoding="utf-8")
        except OSError:
            continue
        for m in _TASK_RE.finditer(text):
            tasks.append(
                {
                    "desc": m.group("desc").strip(),
                    "date": m.group("date"),
                    "source_rel": rel,
                    "source_title": _title_for(rel),
                }
            )
    return tasks


def render_upcoming(tasks: list[dict], *, today: date | None = None) -> str:
    today = today or date.today()
    lines = [
        "# Upcoming",
        "",
        "Regenerated by `chronicle process` / `init-vault-structure` — edit tasks in their source notes, not here.",
        "",
    ]

    # Calendar-invalid dates (e.g. 2026-02-30) skip just that task — one bad
    # note must never abort the whole regeneration.
    dated: list[tuple[date, dict]] = []
    for t in tasks:
        try:
            dated.append((date.fromisoformat(t["date"]), t))
        except ValueError:
            log.debug(
                "skipping task with invalid date %r in %s", t["date"], t["source_rel"]
            )

    overdue = [t for d, t in dated if d < today]
    overdue.sort(key=lambda t: t["date"])
    if overdue:
        lines.append("## Overdue")
        lines.append("")
        for t in overdue:
            lines.append(
                f"- [ ] {t['desc']} 📅 {t['date']} — [[{t['source_rel'][:-3]}|{t['source_title']}]]"
            )
        lines.append("")

    by_month: dict[str, list[dict]] = defaultdict(list)
    for d, t in dated:
        if d < today:
            continue
        by_month[f"{d.year:04d}-{d.month:02d}"].append(t)

    for key in sorted(by_month):
        year, month = key.split("-")
        label = f"{month_name[int(month)]} {year}"
        lines.append(f"## {label}")
        lines.append("")
        for t in sorted(by_month[key], key=lambda t: t["date"]):
            lines.append(
                f"- [ ] {t['desc']} 📅 {t['date']} — [[{t['source_rel'][:-3]}|{t['source_title']}]]"
            )
        lines.append("")

    if not overdue and not by_month:
        lines.append("Nothing scheduled. Tasks with a 📅 date in any note appear here automatically.")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def regenerate_upcoming(root: Path, *, dry_run: bool = False, today: date | None = None) -> bool:
    """Rebuild Upcoming.md at vault root. Returns True if written/would-write."""
    tasks = find_tasks(root)
    content = render_upcoming(tasks, today=today)
    return write_if_changed(root / UPCOMING_PATH, content, dry_run=dry_run)
