//! Upcoming.md regeneration (upcoming.py): unchecked 📅 tasks across PARA notes.

use std::path::Path;

use chrono::{NaiveDate, Utc};
use regex::Regex;
use serde_json::json;

use crate::errors::ChronicleError;
use crate::notes::write_if_changed;
use crate::path_map;

pub const UPCOMING_PATH: &str = "Upcoming.md";

fn task_re() -> Regex {
    // ^[ \t]*-\s\[\s\]\s(?P<desc>.+?)\s*📅\s*(?P<date>\d{4}-\d{2}-\d{2})\s*$
    Regex::new(r"(?m)^[ \t]*-\s\[\s\]\s(.+?)\s*📅\s*(\d{4}-\d{2}-\d{2})\s*$").unwrap()
}

struct Task {
    desc: String,
    date: String,
    source_rel: String,
    source_title: String,
}

/// regenerate_upcoming — whole-file regen; source notes are the SoT.
pub fn regenerate_upcoming(root: &Path, dry_run: bool) -> Result<bool, ChronicleError> {
    let mut tasks: Vec<Task> = Vec::new();
    let re = task_re();
    for (rel, path) in path_map::iter_knowledge_md(root) {
        let Ok(bytes) = std::fs::read(&path) else { continue };
        let text = String::from_utf8_lossy(&bytes).to_string();
        for cap in re.captures_iter(&text) {
            let desc = cap.get(1).map(|m| m.as_str().trim().to_string()).unwrap_or_default();
            let date = cap.get(2).map(|m| m.as_str().to_string()).unwrap_or_default();
            let title = path
                .file_stem()
                .map(|s| s.to_string_lossy().replace(['-', '_'], " "))
                .unwrap_or_default();
            tasks.push(Task { desc, date, source_rel: rel.clone(), source_title: title });
        }
    }

    let today = Utc::now().date_naive();
    let mut overdue: Vec<&Task> = Vec::new();
    let mut future: Vec<(String, Vec<&Task>)> = Vec::new();
    for t in &tasks {
        match NaiveDate::parse_from_str(&t.date, "%Y-%m-%d") {
            Ok(d) => {
                if d < today {
                    overdue.push(t);
                } else {
                    let key = t.date[..7].to_string();
                    if let Some(bucket) = future.iter_mut().find(|(k, _)| *k == key) {
                        bucket.1.push(t);
                    } else {
                        future.push((key, vec![t]));
                    }
                }
            }
            Err(_) => continue, // invalid calendar dates skip that task
        }
    }
    overdue.sort_by(|a, b| a.date.cmp(&b.date));
    future.sort_by(|a, b| a.0.cmp(&b.0));
    for (_, bucket) in future.iter_mut() {
        bucket.sort_by(|a, b| a.date.cmp(&b.date));
    }

    fn bullet(t: &Task) -> String {
        let link_target = t.source_rel.trim_end_matches(".md");
        format!(
            "- [ ] {} \u{1F4C5} {} — [[{}|{}]]",
            t.desc, t.date, link_target, t.source_title
        )
    }

    let mut lines: Vec<String> = vec![
        "# Upcoming".into(),
        String::new(),
        "Regenerated by `chronicle process` / `init-vault-structure` — edit tasks in their source notes, not here.".into(),
        String::new(),
        "## Overdue".into(),
        String::new(),
    ];
    for t in &overdue {
        lines.push(bullet(t));
    }
    lines.push(String::new());
    const MONTHS: [&str; 12] = [
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December",
    ];
    for (key, bucket) in &future {
        let mut parts = key.split('-');
        let y: i32 = parts.next().and_then(|v| v.parse().ok()).unwrap_or(0);
        let m: usize = parts.next().and_then(|v| v.parse().ok()).unwrap_or(1);
        let month_name = MONTHS.get(m.saturating_sub(1)).copied().unwrap_or("January");
        lines.push(format!("## {month_name} {y}"));
        lines.push(String::new());
        for t in bucket {
            lines.push(bullet(t));
        }
        lines.push(String::new());
    }
    if overdue.is_empty() && future.is_empty() {
        lines.push("Nothing scheduled. Tasks with a 📅 date in any note appear here automatically.".into());
        lines.push(String::new());
    }
    let content = format!("{}\n", lines.join("\n").trim_end());

    let path = root.join(UPCOMING_PATH);
    write_if_changed(&path, &content, dry_run)
}
